### ISSUE TITLE
Conflict with rustaceanvim when switching sessions

### ISSUE THREAD

**Issue by xzbdmw** [coffebar/neovim-project#28] opened 2024-03-08 21:00 UTC
Original issue is here
https://github.com/mrcjkb/rustaceanvim/issues/275#issue-2169236225
before this commit https://github.com/mrcjkb/rustaceanvim/commit/5fb048d9a59872547f9ed94b964cf4b35ed6c2fc there are no problem

**Comment by coffebar** [comment] 2024-03-09 08:28
hi, it seems not a bug that can be fixed by nvim-project, maybe you should solve it by yourself using [autocmd](https://github.com/coffebar/dotfiles/blob/main/.config%2Fnvim%2Flua%2Fcoffebar%2Fcommands.lua#L227) after session load to restart or remove everything you want

**Comment by coffebar** [comment] 2024-03-17 10:35
@xzbdmw 
Did you find a solution?

**Comment by xzbdmw** [comment] 2024-04-06 17:46
Hmm, currently stick with the old version of rustaceanvim

**Comment by coffebar** [comment] 2024-04-06 19:01
Install branch [feat_timeout_opt](https://github.com/coffebar/neovim-project/tree/feat_timeout_opt) and experiment with the `filetype_autocmd_timeout` option. It's added to this branch. Maybe 0 value will suit you. If not, try bigger value (1500). 
Hope this will help.

**Comment by coffebar** [comment] 2024-04-07 11:53
@xzbdmw if it will fix your issue, this branch will be merged to main

**Comment by xzbdmw** [comment] 2024-04-07 12:26
Hmm, I set that value to either 200 or 0, still have same problem <img width="783" alt="截屏2024-04-07 20 24 49" src="https://github.com/coffebar/neovim-project/assets/97848247/bea05b79-4a9c-43b8-9ab3-73ee52652705">

**Comment by coffebar** [comment] 2024-04-08 07:54
The branch was merged to main

**Closed** 2024-04-08 12:14 UTC
